apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-qtodelcv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-qtodelcv:d773aa8c12293c75b450966a1d8507f3d5832b3e@sha256:b2033cbeea045db24aa5f85dc76e06702c0d2c15a65c9218b95b4ecf50bcea2d
          name: container-image
